import type { UserRole } from '@prisma/client'

/** Granular permission constants */
export const PERMISSIONS = {
  KNOWLEDGE_READ: 'KNOWLEDGE_READ',
  KNOWLEDGE_WRITE: 'KNOWLEDGE_WRITE',
  KNOWLEDGE_DELETE: 'KNOWLEDGE_DELETE',
  ANALYTICS_VIEW: 'ANALYTICS_VIEW',
  ANALYTICS_EXPORT: 'ANALYTICS_EXPORT',
  PREDICTIONS_VIEW: 'PREDICTIONS_VIEW',
  WORKFLOWS_VIEW: 'WORKFLOWS_VIEW',
  WORKFLOWS_CREATE: 'WORKFLOWS_CREATE',
  WORKFLOWS_EXECUTE: 'WORKFLOWS_EXECUTE',
  WORKFLOWS_DELETE: 'WORKFLOWS_DELETE',
  AGENTS_USE: 'AGENTS_USE',
  AGENTS_CONFIGURE: 'AGENTS_CONFIGURE',
  TEAM_MANAGE: 'TEAM_MANAGE',
  BILLING_MANAGE: 'BILLING_MANAGE',
  SETTINGS_MANAGE: 'SETTINGS_MANAGE',
  ADMIN_IMPERSONATE: 'ADMIN_IMPERSONATE',
  AUDIT_VIEW: 'AUDIT_VIEW',
  AUDIT_EXPORT: 'AUDIT_EXPORT',
  API_KEYS_MANAGE: 'API_KEYS_MANAGE',
  INVENTORY_VIEW: 'INVENTORY_VIEW',
  INVENTORY_MANAGE: 'INVENTORY_MANAGE',
} as const

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]

export const ALL_PERMISSIONS = Object.values(PERMISSIONS)

const READ_ONLY: Permission[] = [
  PERMISSIONS.KNOWLEDGE_READ,
  PERMISSIONS.ANALYTICS_VIEW,
  PERMISSIONS.PREDICTIONS_VIEW,
  PERMISSIONS.WORKFLOWS_VIEW,
  PERMISSIONS.AGENTS_USE,
]

const MANAGER_PLUS: Permission[] = [
  ...READ_ONLY,
  PERMISSIONS.KNOWLEDGE_WRITE,
  PERMISSIONS.WORKFLOWS_CREATE,
  PERMISSIONS.WORKFLOWS_EXECUTE,
  PERMISSIONS.TEAM_MANAGE,
  PERMISSIONS.INVENTORY_VIEW,
  PERMISSIONS.INVENTORY_MANAGE,
]

const FINANCE: Permission[] = [
  ...READ_ONLY,
  PERMISSIONS.ANALYTICS_EXPORT,
  PERMISSIONS.KNOWLEDGE_READ,
  PERMISSIONS.BILLING_MANAGE,
]

const SALES: Permission[] = [
  ...READ_ONLY,
  PERMISSIONS.KNOWLEDGE_WRITE,
  PERMISSIONS.WORKFLOWS_EXECUTE,
  PERMISSIONS.AGENTS_USE,
]

/** Role → permission matrix */
export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  OWNER: ALL_PERMISSIONS,
  CEO: ALL_PERMISSIONS.filter((p) => p !== PERMISSIONS.ADMIN_IMPERSONATE),
  MANAGER: MANAGER_PLUS,
  FINANCE_OFFICER: FINANCE,
  SALES_OFFICER: SALES,
  EMPLOYEE: READ_ONLY,
}

export function permissionsForRole(role: UserRole): Permission[] {
  return ROLE_PERMISSIONS[role] ?? READ_ONLY
}

export function isOwnerOrAdminRole(role: UserRole): boolean {
  return role === 'OWNER' || role === 'CEO'
}
