export {
  LazyDataTable,
  LazyRevenueChart,
  LazyMasterDashboardCharts,
  LazyWorkflowBuilder,
  LazyWorkflowAnalytics,
  LazySalesForecastChart,
  LazySupplierRiskMatrix,
  LazyKPIScorecard,
  LazyFormRichText,
  LazyChartPanel,
  LazyCommandPalette,
  LazyMetricSparkline,
  LazyMasterDashboardClient,
  LazyFinanceDashboardClient,
  LazyInventoryDashboardClient,
  LazyHrDashboardClient,
  LazyCrmDashboardClient,
  LazyCrmAnalyticsClient,
  LazyPipelineKanbanClient,
  LazyAnalyticsPageContent,
  LazyChatInterface,
  LazyPredictionsPageClient,
  LazyWorkflowsPageClient,
  LazyFallback,
  PageFallback,
} from './components'
